#!/usr/bin/env bash
#
# shellcheck disable=SC2009

# Find the PID(s) of the process named 4-to_infinity_and_beyond and kill them
pids=$(pgrep -f 4-to_infinity_and_beyond)

if [ -z "$pids" ]; then
  echo "No process named 4-to_infinity_and_beyond found."
else
  echo "Killing process(es) with PID(s): $pids"
  kill $pids
fi
