#!/usr/bin/env bash
#
# shellcheck disable=SC2009

pids=$(pgrep -f 4-to_infinity_and_beyond)

if [ -n "$pids" ]; then
  read -r -a pid_array <<< "$pids"
  for pid in "${pid_array[@]}"; do
    kill "$pid"
  done
fi
