#!/usr/bin/env bash
# Script that prints a message indefinitely and handles SIGTERM gracefully

term_handler() {
  echo "I am invincible!!!"
}

trap term_handler SIGTERM

while true; do
  echo "To infinity and beyond indefinitely."
  sleep 2
done
