#!/usr/bin/env bash
# This script provides information about the file named "school"

# Check if the file "school" exists
if [ -e "school" ]; then
    echo "school file exists"

    # Check if it's a regular file
    if [ -f "school" ]; then
        # Check if the file is empty
        if [ ! -s "school" ]; then
            echo "school file is empty"
        else
            echo "school file is not empty"
        fi
    else
        echo "school is not a regular file"
    fi
else
    echo "school file does not exist"
fi
